### PR TITLE
add dependency columns

### PR DESCRIPTION
**Pull request by sni**
this pr add 4 new columns for hosts and services with dependency information.

  - depends_exec: list of all hosts this hosts depends on to execute
  - depends_exec_with_info: list of all hosts this hosts depends on to execute including information: host_name, failure_options, dependency_period and inherits_parent
  - depends_notify: list of all hosts this hosts depends on to notify
  - depends_notify_with_info: list of all hosts this hosts depends on to notify including information: host_name, failure_options, dependency_period and inherits_parent

and the same for services.

Signed-off-by: Sven Nierlein <sven@nierlein.de>

### CODE REVIEW

**Comment by jacobbaungard** [comment]
Looks good but I wonder if AuthUser is specified in the request, could it then be possible that the new columns could potentially include services which normally shouldn't be shown to the user? Especially if service_authorization is strict.

**Comment by sni** [comment]
Yes, that might reveil services or hosts which the current user is usually not allowed to see. But it will only reveil the hostname and the service description.

I just checked how other columns handle this, ex.: host parents and they filter the list according the permissions... I will add that as well.

**Comment by sni** [comment]
ok, i added authentication handling. thanks for the review.

**Comment by sni** [comment]
sorry, one more commit. I initially thougt service parents will be converted to service dependencies internally and show up in the dependency lists, but thats not the case. So adding another column for parents to catch them as well.
At least its a very small commit :)

**Pull request merged**
