### PR TITLE
improve log entry tagging

### PR DESCRIPTION
**Pull request by sni**
- add host/service for NOTIFICATION SUPPRESSED and INFO entries.
- add host/service for external commands

### CODE REVIEW

**Review by jacobbaungard — COMMENTED** [review]
I'm not very familiar with the log functionality of Livestatus. So just for my understanding, with this PR we ensure we are correctly parsing the log entries:

`HOST NOTIFICATION SUPPRESSED`
`HOST INFO: `
as well as:
`EXTERNAL COMMAND: cmd_here` (whereas before we would only parse without the space?)

**Comment by sni** [comment]
The hole point of this change is to fill the host and service columns when requesting logs.
Adding the space was just for consistency reasons, the main change was to detect `_HOST` and `_SVC` to match host/service commands.
Thinking about it, i need to make sure to not match _HOSTGROUP commands.

**Comment by sni** [comment]
ok, should be better now.

**Review by jacobbaungard — APPROVED** [review]
Ok, thanks for the explanation. Looks OK to me.

**Pull request merged**
