### PR TITLE
Feature/sync with upstream

### PR DESCRIPTION
**Pull request by mattiasr**
Our local repo was not in sync with upstream since @sni did some merges to upstream.

This PR will make them both in sync again.

### CODE REVIEW

**Comment by mattiasr** [comment]
@sni can you check why we get apt-get errors?

**Comment by sni** [comment]
I will have a look. Could you please meanwhile rebase your changes on latest HEAD?

**Comment by mattiasr** [comment]
rebased

**Comment by sni** [comment]
Thanks, looks much better now.

**Comment by mattiasr** [comment]
@sni can you please look at the travis builds if we can get the apt problems solved.
I only have one week left at OP5, and would like to sort this before :)

**Comment by sni** [comment]
i cannot promise anything, i am on vacation already and have barely time. i will try to have a look.

**Comment by sni** [comment]
please review and merge #26, this should do the trick.

**Comment by jacobbaungard** [comment]
Closing due to: https://github.com/naemon/naemon-livestatus/pull/34

**Pull request closed without merging**
