### PR TITLE
fix-el8-crash

### PR DESCRIPTION
**Pull request by pbiering**
split-out to dedicated patch only

### CODE REVIEW

**Comment by pbiering** [comment]
this superseeds https://github.com/naemon/naemon-livestatus/pull/72

**Comment by jacobbaungard** [comment]
Hi @pbiering,

Starting to work through these (slowly). Thanks again for sending in the patches.

For this one, I can replicate the exact issue when installing from the repos, but for some reason, not when I am compiling the 1.2.0 release from source myself. Did you manage to replicate the issue when building from source, too?

Wonder if there are some gcc/glibc changes which are triggering this issues.

**Comment by jacobbaungard** [comment]
Merged here: https://github.com/naemon/naemon-livestatus/commit/341eccc1ccfbf8bf31a1c2092f16ed2d573369b9

Thanks for the PR, I will try to get around to the rest tomorrow!

**Comment by pbiering** [comment]
> For this one, I can replicate the exact issue when installing from the repos, but for some reason, not when I am compiling the 1.2.0 release from source myself. Did you manage to replicate the issue when building from source, too?

Haven' tested because target is stability on EL8

> Wonder if there are some gcc/glibc changes which are triggering this issues.

as also compiled with "clang" has not bring up the issue I assume either huge code optimization or additional security mechanism inserted during compilation with gcc

**Comment by jacobbaungard** [comment]
I tested the new daily build (https://build.opensuse.org/package/binaries/home:naemon:daily/naemon-livestatus/CentOS_8_Stream) and it seems to work fine, so that's great news. Thanks again for the PR!

**Pull request closed without merging**
